// AUTO-GENERATED by generate_exports.ps1 - DO NOT EDIT.
// One stub per real EOSSDK export; every one returns 0 (EOS_Success / NULL).
// __stdcall arg counts come from the export's @N decoration so the stack is
// balanced; src_* are libsamplerate cdecl exports.

extern "C" int __stdcall EOS_Shutdown(void) { return 0; }
extern "C" int __stdcall EOS_GetVersion(void) { return 0; }
extern "C" int __stdcall EOS_Audio_RemoveNotifyDevicesChanged(void) { return 0; }
extern "C" int __stdcall EOS_Mercury_Shutdown(void) { return 0; }
extern "C" int __stdcall EOS_Platform_GetAntiCheatClientInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_CreateNewOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_DestroyInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_DestroyOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_Create(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetAntiCheatServerInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetAchievementsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_FileMetadata_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Sanctions_PlayerSanction_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_CreateNewInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_Transaction_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_StartInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_StartOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_StopInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_StopOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_EpicAccountId_IsValid(void* a0) { return 0; }
extern "C" int __stdcall EOS_EpicAccountId_FromString(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_StartOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_FileMetadata_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_QueryInputDevices(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_QueryOutputDevices(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_RegisterUser(void* a0) { return 0; }
extern "C" int __stdcall EOS_KWS_PermissionStatus_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_StartInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetFriendsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_StopInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorageFileTransferRequest_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_StopOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_UI_GetNotificationLocationPreference(void* a0) { return 0; }
extern "C" int __stdcall EOS_Auth_GetLoggedInAccountsCount(void* a0) { return 0; }
extern "C" int __stdcall EOS_Initialize(void* a0) { return 0; }
extern "C" int __stdcall EOS_PresenceModification_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Auth_IdToken_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_CheckForLauncherAndRestart(void* a0) { return 0; }
extern "C" int __stdcall EOS_Auth_Token_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_UnregisterUser(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetAuthInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorageFileTransferRequest_GetFileRequestState(void* a0) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorageFileTransferRequest_CancelRequest(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetRTCInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_EResult_IsOperationComplete(void* a0) { return 0; }
extern "C" int __stdcall EOS_EResult_ToString(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_CatalogItem_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_CatalogOffer_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_CatalogRelease_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetRTCAdminInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetReportsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetProgressionSnapshotInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetPlayerDataStorageInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetP2PInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetModsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetMetricsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetLobbyInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetLeaderboardsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetKWSInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetPresenceInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_IsInputStreamSilent(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetSanctionsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetStatsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_TitleStorageFileTransferRequest_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_Tick(void* a0) { return 0; }
extern "C" int __stdcall EOS_Connect_ExternalAccountInfo_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetConnectInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetCustomInvitesInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Connect_GetLoggedInUsersCount(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetEcomInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetSessionsInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_KeyImageInfo_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Connect_IdToken_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_TitleStorageFileTransferRequest_CancelRequest(void* a0) { return 0; }
extern "C" int __stdcall EOS_Stats_Stat_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetUserInfoInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetUIInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Platform_GetTitleStorageInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_TitleStorageFileTransferRequest_GetFileRequestState(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_IsInputStreamDeviceDisconnected(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_Entitlement_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_Definition_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Presence_Info_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_Attribute_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_ProductUserId_FromString(void* a0) { return 0; }
extern "C" int __stdcall EOS_ProductUserId_IsValid(void* a0) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Mods_ModInfo_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_SessionModification_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_UserInfo_ExternalUserInfo_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Lobby_Attribute_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_ActiveSession_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_ActiveSession_Info_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Achievements_UnlockedAchievement_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Mercury_Initialize(void* a0) { return 0; }
extern "C" int __stdcall EOS_RTCAdmin_UserToken_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Achievements_PlayerAchievement_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Achievements_Definition_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Achievements_DefinitionV2_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Logging_SetCallback(void* a0) { return 0; }
extern "C" int __stdcall EOS_UserInfo_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_Info_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_Info_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_DestroyInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_DestroyOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_EnableCommunicationsModeOutputDevices(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_CreateNewInputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_RTC_GetAudioInterface(void* a0) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_LeaderboardDefinition_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Audio_CreateNewOutputStream(void* a0) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_LeaderboardUserScore_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_LeaderboardRecord_Release(void* a0) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetOfferImageInfoCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetOfferItemCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetTransactionCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Metrics_EndPlayerSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Metrics_BeginPlayerSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_SetParameter(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_KWS_GetPermissionsCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_GetLeaderboardUserScoreCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_SetMaxResults(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetOfferCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_SetPortRange(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetItemReleaseCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_SetSessionId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_GetLeaderboardDefinitionCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_SetHostAddress(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_SetBucketId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_SetInvitesAllowed(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_SetJoinInProgressAllowed(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetEntitlementsCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_RemoveParameter(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetItemImageInfoCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_SetPermissionLevel(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_GetLeaderboardRecordCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Logging_SetLogLevel(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_GetSearchResultCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Lobby_GetInviteCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Sessions_DumpSessionState(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_SetMaxPlayers(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_SetTargetUserId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_RemoveAttribute(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_SendPacket(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_RemoveAttribute(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_ClearPacketQueue(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_AddMemberAttribute(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_AddAttribute(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_GetSessionAttributeCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Friends_GetFriendAtIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_GetMemberCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_GetMemberByIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_GetMemberAttributeCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Friends_GetFriendsCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_GetLobbyOwner(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_GetAttributeCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Friends_GetStatus(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_AcceptConnection(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_SetRelayControl(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_CloseConnection(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Sessions_IsUserInSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_RemoveMemberAttribute(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_SetInvitesAllowed(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_SetTargetUserId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_SetParameter(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_SetMaxResults(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_SetLobbyId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_RemoveParameter(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Sessions_GetInviteCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_GetSearchResultCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_GetAudioOutputDevicesCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_CloseConnections(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_SessionModification_AddAttribute(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_P2P_SetPacketQueueSize(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_Transaction_GetEntitlementsCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Sanctions_GetPlayerSanctionCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_SetPermissionLevel(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_SetMaxMembers(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_LobbyModification_SetBucketId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RegisterPlatformAudioUser(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Platform_SetOverrideLocaleCode(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Presence_HasPresence(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_ReceiveMessageFromClient(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_RegisterClient(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_RegisterEvent(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UserInfo_GetExternalUserInfoCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Ecom_GetEntitlementsByNameCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_AddExternalIntegrityCatalog(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_ActiveSession_GetRegisteredPlayerCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_SetClientDetails(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_SetClientNetworkState(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_SetGameSessionId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_UnregisterClient(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Audio_GetInputDeviceInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Audio_GetInputStreamInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Audio_GetOutputDeviceInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_ActiveSession_GetRegisteredPlayerByIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_SetAudioOutputSettings(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_SetAudioInputSettings(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UI_IsValidKeyCombination(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerUseWeapon(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerUseAbility(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerTick(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_EndSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_ReceiveMessageFromPeer(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_ReceiveMessageFromServer(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_RegisterPeer(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_ProgressionSnapshot_AddProgression(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_BeginSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_UnregisterPeer(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UI_SetToggleFriendsKey(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_ProgressionSnapshot_EndSnapshot(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UI_SetDisplayPreference(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_EndSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogEvent(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogGameRoundEnd(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogGameRoundStart(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerDespawn(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerRevive(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerSpawn(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_LogPlayerTakeDamage(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_BeginSession(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Audio_GetOutputStreamInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_SendAudio(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_GetInputStreamInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_GetOutputStreamInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_PushPacketToOutputStream(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_SetEncoderSettings(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_SetMicProcessingSettings(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTC_SetRoomSetting(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTC_SetSetting(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_GetAudioInputDeviceByIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Connect_GetExternalAccountMapping(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Connect_GetLoggedInUserByIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Connect_GetLoginStatus(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Connect_GetProductUserExternalAccountCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_GetAudioInputDevicesCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Platform_SetOverrideCountryCode(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Stats_GetStatsCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_FinalizeInvite(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_SetCustomInvite(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_GetAudioOutputDeviceByIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Achievements_GetUnlockedAchievementCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_GetCurrentMicAmplitude(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_UnregisterPlatformAudioUser(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_GetFileMetadataCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Achievements_GetPlayerAchievementCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Achievements_GetAchievementDefinitionCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_PresenceModification_SetStatus(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UI_AcknowledgeEventId(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_PresenceModification_DeleteData(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Auth_GetMergedAccountsCount(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_PresenceModification_SetRawRichText(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UI_GetToggleFriendsKey(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_PresenceModification_SetData(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Auth_GetLoginStatus(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_BroadcastAudio_GetCurrentGainLevel(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_Auth_GetLoggedInAccountByIndex(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_UI_GetFriendsVisible(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_PresenceModification_SetJoinInfo(void* a0, void* a1) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RemoveNotifyAudioOutputState(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAdmin_CopyUserTokenByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RemoveNotifyAudioBeforeRender(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RemoveNotifyAudioBeforeSend(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RemoveNotifyAudioInputState(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAdmin_CopyUserTokenByUserId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_UpdateLobbyModification(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RemoveNotifyAudioDevicesChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Mods_CopyModInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_RemoveNotifyParticipantUpdated(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Platform_GetOverrideCountryCode(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_ProductUserId_ToString(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Platform_GetOverrideLocaleCode(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyRTCRoomConnectionChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sanctions_CopyPlayerSanctionByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_CopyFileMetadataAtIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_CopyFileMetadataByFilename(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_GetFileMetadataCount(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTC_RemoveNotifyParticipantStatusChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTC_RemoveNotifyDisconnected(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_RemoveNotifyPeerConnectionRequest(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_RemoveNotifyPeerConnectionEstablished(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_RemoveNotifyPeerConnectionClosed(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_RemoveNotifyIncomingPacketQueueFull(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_GetRelayControl(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_CopyInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_GetPacketQueueInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_GetNextReceivedPacketSize(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_P2P_GetNATType(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Presence_CopyPresence(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Presence_CreatePresenceModification(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_CopySessionAttributeByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_SessionDetails_CopySessionAttributeByKey(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Presence_RemoveNotifyJoinGameAccepted(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Presence_RemoveNotifyOnPresenceChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_ProgressionSnapshot_BeginSnapshot(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyLobbyUpdateReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_KWS_CopyPermissionByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyLobbyMemberStatusReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Auth_GetSelectedAccountId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Auth_RemoveNotifyLoginStatusChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_CopyFileMetadataByFilename(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_CopyIdToken(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_CopyProductUserExternalAccountByAccountId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_CopyProductUserExternalAccountByAccountType(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_CopyProductUserExternalAccountByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_CopyProductUserInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_CopyFileMetadataAtIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_RemoveNotifyAuthExpiration(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Connect_RemoveNotifyLoginStatusChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Stats_CopyStatByName(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Stats_CopyStatByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_ContinuanceToken_ToString(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_UpdateSessionModification(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyLobbyMemberUpdateReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_RemoveNotifyCustomInviteReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyEntitlementById(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyEntitlementByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyEntitlementByNameAndIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyItemById(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyItemImageInfoByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyItemReleaseByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Auth_GetMergedAccountByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Auth_CopyIdToken(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Audio_SetNotifyDevicesChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Audio_SetFeatureEnabledForInputStream(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyAchievementDefinitionByAchievementId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyAchievementDefinitionByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyAchievementDefinitionV2ByAchievementId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyAchievementDefinitionV2ByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyPlayerAchievementByAchievementId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyPlayerAchievementByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyUnlockedAchievementByAchievementId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_CopyUnlockedAchievementByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Achievements_RemoveNotifyAchievementsUnlocked(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_ActiveSession_CopyInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_UserInfo_CopyUserInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyOfferById(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_UserInfo_CopyExternalUserInfoByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_UserInfo_CopyExternalUserInfoByAccountType(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_UserInfo_CopyExternalUserInfoByAccountId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_RemoveNotifyMessageToPeer(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_RemoveNotifyMessageToServer(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_RemoveNotifyPeerActionRequired(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_RemoveNotifyPeerAuthStatusChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_UI_RemoveNotifyDisplaySettingsUpdated(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_GetProtectMessageOutputLength(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_RemoveNotifyClientActionRequired(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_RemoveNotifyClientAuthStatusChanged(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_RemoveNotifyMessageToClient(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_GetProtectMessageOutputLength(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyOfferByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_RemoveNotifyCustomInviteAccepted(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyOfferItemByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyOfferImageInfoByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_CopyLeaderboardRecordByUserId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_CopyLeaderboardUserScoreByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_CopyLeaderboardUserScoreByUserId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_CreateSessionModification(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_CopySessionHandleForPresence(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_CopySessionHandleByUiEventId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_CopyAttributeByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_CopyAttributeByKey(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_CopyInfo(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_CopyMemberAttributeByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_CopyLeaderboardDefinitionByLeaderboardId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_LobbyDetails_CopyMemberAttributeByKey(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_CopySessionHandleByInviteId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_CopyActiveSessionHandle(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_CopyLobbyDetailsHandle(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_CopyLobbyDetailsHandleByInviteId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_CopyLobbyDetailsHandleByUiEventId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_CreateLobbySearch(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_IsRTCRoomConnected(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_CopySearchResultByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyJoinLobbyAccepted(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyLobbyInviteAccepted(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Lobby_RemoveNotifyLobbyInviteReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_CopySearchResultByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_CopyLeaderboardDefinitionByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_CopyLeaderboardRecordByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_KWS_GetPermissionByKey(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyTransactionById(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_CopyTransactionByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_CreateSessionSearch(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_Transaction_GetTransactionId(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Ecom_Transaction_CopyEntitlementByIndex(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_RemoveNotifySessionInviteReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_RemoveNotifySessionInviteAccepted(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Sessions_RemoveNotifyJoinSessionAccepted(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_KWS_RemoveNotifyPermissionsUpdateReceived(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_Friends_RemoveNotifyFriendsUpdate(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_EpicAccountId_ToString(void* a0, void* a1, void* a2) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_UpdateReceiving(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_AddNotifySessionInviteReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_AddNotifySessionInviteAccepted(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_AddNotifyJoinSessionAccepted(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sanctions_QueryActivePlayerSanctions(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_UserInfo_QueryUserInfo(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_UnregisterPlayers(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_UserInfo_QueryUserInfoByDisplayName(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_UserInfo_QueryUserInfoByExternalAccount(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_SessionSearch_Find(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_SendInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_StartSession(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_UpdateSession(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_RejectInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_UpdateSending(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_QueryInvites(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_DeleteCache(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_QueryFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_QueryFileList(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_TitleStorage_ReadFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTC_LeaveRoom(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTC_JoinRoom(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_UI_AddNotifyDisplaySettingsUpdated(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_DestroySession(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_EndSession(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_RegisterPlayers(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_GetInviteIdByIndex(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTC_BlockParticipant(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_TitleStorageFileTransferRequest_GetFilename(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Stats_QueryStats(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTC_AddNotifyParticipantStatusChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Stats_IngestStat(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTC_AddNotifyDisconnected(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Sessions_JoinSession(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_UI_ShowFriends(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Reports_SendPlayerBehaviorReport(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_UI_HideFriends(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Achievements_AddNotifyAchievementsUnlocked(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_DestroyLobby(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_AddNotifyAudioOutputState(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_DeleteDeviceId(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_GetProductUserIdMapping(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_LinkAccount(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_Login(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_QueryExternalAccountMappings(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_QueryProductUserIdMappings(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_TransferDeviceIdAccount(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_UnlinkAccount(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_VerifyIdToken(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_AddNotifyCustomInviteAccepted(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_AddNotifyCustomInviteReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_CustomInvites_SendCustomInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_CreateUser(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Ecom_Checkout(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Ecom_QueryOffers(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Ecom_QueryOwnership(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Ecom_QueryOwnershipToken(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Ecom_RedeemEntitlements(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Friends_AcceptInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_AddNotifyParticipantUpdated(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Friends_QueryFriends(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Friends_RejectInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Friends_SendInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_KWS_AddNotifyPermissionsUpdateReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_KWS_CreateUser(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_KWS_QueryAgeGate(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Ecom_QueryEntitlements(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_KWS_QueryPermissions(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_CreateDeviceId(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_AddNotifyAuthExpiration(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Achievements_AddNotifyAchievementsUnlockedV2(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Achievements_QueryDefinitions(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Achievements_QueryPlayerAchievements(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Achievements_UnlockAchievements(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_AddNotifyMessageToPeer(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_AddNotifyMessageToServer(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_AddNotifyPeerActionRequired(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_AddNotifyPeerAuthStatusChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_PollStatus(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_ProtectMessage(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatClient_UnprotectMessage(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_AddNotifyClientActionRequired(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Connect_AddNotifyLoginStatusChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_AddNotifyClientAuthStatusChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_ProtectMessage(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_UnprotectMessage(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_AddNotifyLoginStatusChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_CopyUserAuthToken(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_DeletePersistentAuth(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_LinkAccount(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_Login(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_Logout(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_QueryIdToken(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_VerifyIdToken(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Auth_VerifyUserAuth(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_ByteArray_ToString(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_AntiCheatServer_AddNotifyMessageToClient(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_KWS_RequestPermissions(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Friends_AddNotifyFriendsUpdate(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_QueryLeaderboardDefinitions(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_GetPortRange(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_QueryNATType(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Platform_GetActiveCountryCode(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Platform_GetActiveLocaleCode(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorageFileTransferRequest_GetFilename(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_DeleteCache(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_KWS_UpdateParentEmail(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_DuplicateFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_QueryFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_QueryFileList(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_ReadFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_WriteFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_AddNotifyPeerConnectionRequest(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Presence_AddNotifyJoinGameAccepted(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Presence_GetJoinInfo(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Presence_QueryPresence(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Presence_SetPresence(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_ProgressionSnapshot_DeleteSnapshot(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_ProgressionSnapshot_SubmitSnapshot(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAdmin_Kick(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAdmin_QueryJoinRoomToken(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAdmin_SetParticipantHardMute(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_AddNotifyAudioBeforeRender(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_AddNotifyAudioBeforeSend(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_AddNotifyAudioDevicesChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_RTCAudio_AddNotifyAudioInputState(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Presence_AddNotifyOnPresenceChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_AddNotifyPeerConnectionEstablished(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_PlayerDataStorage_DeleteFile(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_AddNotifyIncomingPacketQueueFull(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_QueryLeaderboardRanks(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Leaderboards_QueryLeaderboardUserScores(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_LobbySearch_Find(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyJoinLobbyAccepted(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_AddNotifyPeerConnectionClosed(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyLobbyInviteReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyLobbyMemberStatusReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyLobbyMemberUpdateReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyLobbyUpdateReceived(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyRTCRoomConnectionChanged(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_CreateLobby(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_GetInviteIdByIndex(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_GetRTCRoomName(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_AddNotifyLobbyInviteAccepted(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_KickMember(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_JoinLobby(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_LeaveLobby(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_PromoteMember(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_QueryInvites(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_RejectInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_SendInvite(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Lobby_UpdateLobby(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Mods_EnumerateMods(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Mods_InstallMod(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Mods_UninstallMod(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_Mods_UpdateMod(void* a0, void* a1, void* a2, void* a3) { return 0; }
extern "C" int __stdcall EOS_P2P_ReceivePacket(void* a0, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6) { return 0; }
extern "C" int src_callback_new(void) { return 0; }
extern "C" int src_callback_read(void) { return 0; }
extern "C" int src_clone(void) { return 0; }
extern "C" int src_delete(void) { return 0; }
extern "C" int src_error(void) { return 0; }
extern "C" int src_float_to_int_array(void) { return 0; }
extern "C" int src_float_to_short_array(void) { return 0; }
extern "C" int src_get_channels(void) { return 0; }
extern "C" int src_get_description(void) { return 0; }
extern "C" int src_get_name(void) { return 0; }
extern "C" int src_get_version(void) { return 0; }
extern "C" int src_int_to_float_array(void) { return 0; }
extern "C" int src_is_valid_ratio(void) { return 0; }
extern "C" int src_new(void) { return 0; }
extern "C" int src_process(void) { return 0; }
extern "C" int src_reset(void) { return 0; }
extern "C" int src_set_ratio(void) { return 0; }
extern "C" int src_short_to_float_array(void) { return 0; }
extern "C" int src_simple(void) { return 0; }
extern "C" int src_strerror(void) { return 0; }
