// ---------------------------------------------------------------------------
// EOSStub — a hard stub for EOSSDK-Win32-Shipping.dll / EOSSDK-Win64-Shipping.dll
//
// Drop-in replacement for the Epic Online Services SDK that does NOTHING: every
// exported function returns 0 and no callback ever fires. This disables EOS
// entirely — auth, achievements, RTC, and crucially the Epic overlay
// (EOSOVH-Win32-Shipping.dll), which the SDK loads on its own and which crashes
// inside Simulated Reality weaving (its hooked-object table chokes on the extra
// D3D swapchains the SR weaver creates — see project_tr2013_sr_dead_end).
//
// We can't block the overlay from our game-folder D3D proxies: EOSSDK is a
// STATIC import, so it (and the overlay) load before any of our other code runs.
// Replacing EOSSDK itself is the only point early enough — and since we ARE the
// module the game imports, we catch every caller regardless of how it resolves
// the function (IAT, GetProcAddress, ordinal).
//
// Return value: 0 is the right "success" here — EOS uses EOS_EResult where
// EOS_Success == 0, and 0 doubles as a NULL handle / EOS_FALSE. EOS_Platform_Create
// returning NULL is the documented "no platform" path, so a well-behaved game
// simply skips EOS. (A game that hard-requires a valid platform, or that blocks
// waiting on a login callback, will misbehave — use the pass-through variant
// there instead.)
//
// Exports are produced by exports_x86.def (auto-generated by generate_exports.ps1
// from the real EOSSDK), which aliases each decorated export name to one of the
// ret-N stubs below.
// ---------------------------------------------------------------------------

#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>
#include <stdio.h>

// The 574 export bodies live in eos_stubs.generated.cpp (one real function per
// real EOSSDK export, each returning 0). They're exported under their exact
// decorated names by exports_<arch>.def. Both files are produced by
// generate_exports.ps1 from whatever EOSSDK version the target game ships, so
// the export set always matches byte-for-byte.

// One-line confirmation written next to the DLL so it's obvious the stub is live.
static void LogLoaded(HINSTANCE hSelf)
{
    wchar_t path[MAX_PATH];
    if (!GetModuleFileNameW(hSelf, path, MAX_PATH)) return;
    wchar_t* slash = wcsrchr(path, L'\\');
    if (!slash) return;
    size_t room = MAX_PATH - (size_t)(slash + 1 - path);
    if (wcscpy_s(slash + 1, room, L"EOSStub.log") != 0) return;

    FILE* f = _wfopen(path, L"a");
    if (!f) return;
    wchar_t exe[MAX_PATH] = L"";
    GetModuleFileNameW(NULL, exe, MAX_PATH);
    fwprintf(f, L"EOSSDK stub attached - EOS (and the Epic overlay) disabled. Host: %s\n", exe);
    fclose(f);
}

BOOL WINAPI DllMain(HINSTANCE hInst, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH)
    {
        DisableThreadLibraryCalls(hInst);
        LogLoaded(hInst);
    }
    return TRUE;
}
