<#
.SYNOPSIS
  Generate the EOSStub export list (.def) and stub bodies (.cpp) from a real
  EOSSDK DLL, so the stub's export set matches that EOSSDK version byte-for-byte.

.DESCRIPTION
  EOSStub replaces EOSSDK-Win32/64-Shipping.dll with a do-nothing stub: every
  export returns 0 (EOS_Success / NULL), disabling EOS entirely including the
  crash-prone Epic overlay. Because the game imports EOSSDK by its exact
  (decorated, on x86) export names, the stub must export the identical set. This
  script reads the real DLL's exports via dumpbin and emits:
    - exports_x86.def / exports_x64.def : the export list for the linker
    - eos_stubs.generated.cpp           : one real stub function per export

  x86 exports are __stdcall and name-decorated (_EOS_Foo@N); the @N gives the
  argument-byte count so each stub balances the stack. x64 exports are
  undecorated (single calling convention). The src_* exports are libsamplerate
  (cdecl) re-exported by EOSSDK.

.EXAMPLE
  .\generate_exports.ps1 -EosDll "S:\...\Tomb Raider\EOSSDK-Win32-Shipping.dll"
#>
param(
    [Parameter(Mandatory = $true)] [string] $EosDll,
    [string] $OutDir = $PSScriptRoot,
    [string] $DumpBin
)

$ErrorActionPreference = "Stop"

if (-not $DumpBin) {
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    if (-not (Test-Path $vswhere)) { $vswhere = "$env:ProgramFiles\Microsoft Visual Studio\Installer\vswhere.exe" }
    $vsRoot = & $vswhere -latest -prerelease -property installationPath
    $DumpBin = Get-ChildItem "$vsRoot\VC\Tools\MSVC\*\bin\HostX64\x86\dumpbin.exe" | Select-Object -First 1 -ExpandProperty FullName
}
# dumpbin /exports needs mspdbcore.dll on PATH
$mspdb = Get-ChildItem (Split-Path (Split-Path (Split-Path $DumpBin))) -Recurse -Filter mspdbcore.dll | Select-Object -First 1
if ($mspdb) { $env:PATH = "$($mspdb.DirectoryName);$env:PATH" }

$raw = & $DumpBin /exports $EosDll
$inTable = $false
$rows = foreach ($line in $raw) {
    if ($line -match '^\s+ordinal\s+hint\s+RVA\s+name') { $inTable = $true; continue }
    if (-not $inTable) { continue }
    if ($line -match '^\s+Summary') { break }
    if ($line -match '^\s+(\d+)\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]{8}\s+(\S+)') {
        $name = $Matches[2]
        $n = 0; if ($name -match '@(\d+)$') { $n = [int]$Matches[1] }
        [pscustomobject]@{ Ordinal = [int]$Matches[1]; Name = $name; ArgBytes = $n }
    }
}
$rows = $rows | Sort-Object Ordinal
$isX86 = [bool]($rows | Where-Object { $_.Name -match '@\d+$' })
Write-Host "Parsed $($rows.Count) exports ($([string]::Format('{0}', $(if($isX86){'x86 / decorated'}else{'x64 / undecorated'})))"

# .def
$def = New-Object System.Text.StringBuilder
[void]$def.AppendLine("; Auto-generated by generate_exports.ps1 from $([System.IO.Path]::GetFileName($EosDll)). Do not hand-edit.")
[void]$def.AppendLine("EXPORTS")
foreach ($r in $rows) { [void]$def.AppendLine("    $($r.Name)") }
$defName = if ($isX86) { "exports_x86.def" } else { "exports_x64.def" }
[System.IO.File]::WriteAllText((Join-Path $OutDir $defName), $def.ToString())

# stub bodies (shared across arch; __stdcall is ignored on x64)
$cpp = New-Object System.Text.StringBuilder
[void]$cpp.AppendLine("// AUTO-GENERATED by generate_exports.ps1 - DO NOT EDIT.")
[void]$cpp.AppendLine("// One stub per real EOSSDK export; every one returns 0 (EOS_Success / NULL).")
[void]$cpp.AppendLine("")
foreach ($r in $rows) {
    if ($r.Name -match '^_?(EOS_.+?)(@(\d+))?$' -and $r.ArgBytes -ne $null -and ($r.Name -match '@\d+$' -or -not $isX86) -and $r.Name -match 'EOS_') {
        $undec = $r.Name -replace '^_', '' -replace '@\d+$', ''
        $nargs = [int]($r.ArgBytes / 4)
        $params = if ($nargs -eq 0) { "void" } else { ((0..($nargs - 1)) | ForEach-Object { "void* a$_" }) -join ", " }
        [void]$cpp.AppendLine("extern `"C`" int __stdcall $undec($params) { return 0; }")
    }
    else {
        $undec = $r.Name -replace '^_', '' -replace '@\d+$', ''
        [void]$cpp.AppendLine("extern `"C`" int $undec(void) { return 0; }")
    }
}
[System.IO.File]::WriteAllText((Join-Path $OutDir "eos_stubs.generated.cpp"), $cpp.ToString())
Write-Host "Wrote $defName and eos_stubs.generated.cpp to $OutDir"
